train_ecommerce/home/urls.py
from django.urls import path, include
from .views import *

app_name = 'home'

bucket_urls = [
    path('', BucketHome.as_view(), name='bucket'),
    path('delete_obj_bucket/<key>', DeleteBucketObject.as_view(), name='delete_obj_bucket'),
]


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:category_slug>', HomeView.as_view(), name='category_filter'),
]

train_ecommerce/orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>', CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>', CartRemoveView.as_view(), name='cart_remove'),
]

train_ecommerce/train_ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

train_ecommerce/home/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    category = models.ManyToManyField('Category', related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField()
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('home:product_detail', args=[self.slug])

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', null=True, blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:category_filter', args=[self.slug])

train_ecommerce/home/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from orders.forms import *
from .models import *
from django.views import View
from . import tasks


class HomeView(View):
    def get(self, request, category_slug=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.all()
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'home/home.html', {'products': products, 'categories': categories})


class ProductDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        form = CartAddForm()
        return render(request, 'home/detail.html', {'product': product, 'form': form})

    def post(self, request):
        ...


class BucketHome(View):
    template_name = 'home/bucket.html'

    def get(self, request):
        objects = tasks.all_bucket_objects_task()
        return render(request, self.template_name, {'objects': objects})


class DeleteBucketObject(View):

    def get(self, request, key):
        tasks.delete_object_task.delay(key)
        messages.success(request, 'your object will be delete soon', 'info')
        return redirect('home:bucket')

train_ecommerce/home/templates/home/bucket.html
{% extends 'base.html' %}


{% block content %}

    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>

        {% for object in objects %}

            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ object.Key }}</td>
                <td>{{ object.Size|filesizeformat }}</td>
                <td><a href="{% url 'home:download_obj_bucket' object.Key  %}">Download</a></td>
                <td><a href="{% url 'home:delete_obj_bucket' object.Key %}">Delete</a></td>
            </tr>

        {% endfor %}

        </tbody>
    </table>

{% endblock %}

train_ecommerce/home/templates/home/detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <h1>{{ product.name }}</h1>
    <small>{{ product.created }}</small><br>
    <p>{{ product.price }}</p>
    <img class='rounded' width="300" src="{{ product.image.url }}" alt="{{ product.name }}">
    <p>{{ product.description }}</p><br><br>

    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="add to cart">
    </form>

{% endblock %}

train_ecommerce/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers%}
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block content %}

    {% for category in categories %}
        <a href="{{ category.get_absolute_url }}" class="btn btn-primary">{{ category.name }}</a>
    {% endfor %}
    <br><br><br><br>
    {% for product in products %}

        <div class="card rounded" style="width: 18rem;display:inline-block;">
          <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
            <div class="card-body">
                <h5 class="card-title"><a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                <p class="card-text">{{ product.description }}</p>
                <a href="{{ product.get_absolute_url }}" class="btn btn-primary">detail</a>
            </div>
        </div>

    {% endfor %}

{% endblock %}