train_ecommerce/home/urls.py
from django.urls import path, include
from .views import *

app_name = 'home'

bucket_urls = [
    path('', BucketHome.as_view(), name='bucket'),
    path('delete_obj_bucket/<key>', DeleteBucketObject.as_view(), name='delete_obj_bucket'),
]


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:category_slug>', HomeView.as_view(), name='category_filter'),
]

train_ecommerce/orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>', CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>', CartRemoveView.as_view(), name='cart_remove'),
]

train_ecommerce/train_ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

train_ecommerce/orders/models.py
from django.db import models

from accounts.models import User
from django.conf import settings
from django.contrib.auth import get_user_model

from home.models import Product


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('paid', '-updated')

    def __str__(self):
        return f'{self.user} - {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def get_total_price(self):
        return sum(item.get_cost() for item in self.items.all)

    def __str__(self):
        return self.id

    def get_cost(self):
        return self.price * self.quantity

train_ecommerce/orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9)

train_ecommerce/orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

from home.models import Product
from orders.cart import Cart
from orders.forms import CartAddForm


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart': cart})

    def post(self):
        ...


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')

train_ecommerce/orders/templates/orders/cart.html
{% extends 'base.html'%}
{% block content %}
    <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">quantity</th>
      <th scope="col">Unit Price</th>
      <th scope="col">total Price</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart %}
      <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ item.product }}</td>
          <td>{{ item.quantity }}</td>
          <td>{{ item.price }}</td>
          <td>{{ item.total_price }}</td>
          <td><a href="{% url 'orders:cart_remove' item.product.id %}">remove</a></td>
      </tr>

  {% endfor %}
    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}