train_ecommerce/accounts/urls.py
from django.urls import path

from accounts.views import *
app_name = 'accounts'

urlpatterns = [
    path('regitser/', UserRegisterView.as_view(), name='user_register'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('verify/', UserRegisterVerifyCodeView.as_view(), name='verify_code')
]

train_ecommerce/home/urls.py
from django.urls import path, include
from .views import *

app_name = 'home'

bucket_urls = [
    path('', BucketHome.as_view(), name='bucket'),
    path('delete_obj_bucket/<key>', DeleteBucketObject.as_view(), name='delete_obj_bucket'),
]


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:category_slug>', HomeView.as_view(), name='category_filter'),
]

train_ecommerce/orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>', CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>', CartRemoveView.as_view(), name='cart_remove'),
]

train_ecommerce/train_ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

train_ecommerce/templates/inc/footer.html
<footer class="bg-dark text-center text-white sticky-bottom">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/s.sajadsafa/" role="button"
        ><i class="fab fa-instagram"></i
      ></a>
      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://linkedin.com/in/cybera3s" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/cybera3s" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2018 - {% now "Y" %} Copyright
    <a class="text-white" href="{% url 'home:home' %}">S.Safa</a>
  </div>
  <!-- Copyright -->
</footer>

train_ecommerce/templates/inc/messages.html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </symbol>
    <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
</svg>
{% if messages %}

    {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
            {% if msg.tags == "danger error" %}
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                    <use xlink:href="#exclamation-triangle-fill"/>
                </svg>
            {% else %}
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
                    <use xlink:href="#check-circle-fill"/>
                </svg>
            {% endif %}
            {{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

        </div>

    {% endfor %}

{% endif %}

train_ecommerce/templates/inc/nav.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold p-2" href="{% url 'home:home' %}">Aiva Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between p-2" id="navbarNav">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>


        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_logout' %}">Logout</a>
            </li>
       {% else %}
             <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:user_login' %}">Login</a>
            </li>
        {% endif %}
        {% if request.user.is_admin %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home:bucket' %}">Bucket</a>
            </li>
        {% endif %} 

      </ul>
    {% if request.user.is_authenticated %}
        <span class="text-white" id="username-nav">{{ request.user.email }}</span>
    {% endif %}
  <a class="nav-link active" aria-current="page" href="{% url 'orders:cart' %}">cart {{ cart|length  }}</a>



    </div>
  </div>
</nav>